### ISSUE TITLE
NTR: Request for S03 15N-tracer addition, incubation

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S03#2]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>15N-tracer addition, incubation, fixation, purge and trap <p><b>Definition</b><p> The sample was spiked with a 15N (nitrogen 15)-labelled substrate and incubated for a set time period.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://www.frontiersin.org/articles/10.3389/fmars.2021.611937/full<p> <p>https://github.com/nvs-vocabs/P01/issues/98</p>

**Comment by gwemon** [comment]
S03468	15N-tracer addition, incubation, fixation, gas purging and trapping created and queued for publication of the NVS

**Comment by gwemon** [comment]
http://vocab.nerc.ac.uk/collection/S03/current/S03468/
