### ISSUE TITLE
NTR: Request for S03 distillation

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S03#3]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>distillation <p><b>Definition</b><p> Separation of the components or substances from a liquid mixture by using selective boiling and condensation.<p><H2> Optional </H2><p><b>Sources/references</b><p> BODCNVS-1088<p>

**Comment by danibodc** [comment]
This term has now been loaded and will be live on the NVS from 0730 UTC tomorrow at:
https://vocab.nerc.ac.uk/collection/S03/current/S03469/
