### ISSUE TITLE
NTR: Request for S03 carbon-13 isotope-labelled tracer addition, dawn-to-dawn on-deck incubation at simulated in-situ light level, filtration

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S03#6]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>carbon-13 isotope-labelled tracer addition, dawn-to-dawn on-deck incubation at simulated in-situ light level, filtration <p><b>Definition</b><p> A Carbon-13 (13C) stable isotope tracer was added to the sample which was held for 24 hours from dawn to dawn, in an on-deck incubator with controlled light levels designed to mimic in-situ light levels at the collection depth and documented elsewhere before filtration to collect the particulate phase.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://jira.ceh.ac.uk/browse/BODCNVS-1325<p>

**Comment by roswri** [comment]
Code created:
S03473 - carbon-13 isotope-labelled tracer addition, dawn-to-dawn on-deck incubation at simulated in-situ light level, filtration
