### ISSUE TITLE
NTR: Request for S03 Strong acid and HF acid digestion

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S03#9]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Strong acid with HF acid digestion <p><b>Definition</b><p> The sample was totally dissolved in a solution of strong acid and hydrofluoric (HF) acid which completely digests silicate-based minerals.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://www.agilent.com/cs/library/applications/application_inert_sample_chamber_icp-oes_5110_5994-1213en_us_agilent.pdf<p>

**Comment by SLBlakeman** [comment]
S03 term created - S03475 - strong acid with HF acid digestion
